export const TEXT_RECIEVED = 'TEXT_RECIEVED';
export const RESTORE_TEXT = 'RESTORE_TEXT';
export const DELETE_TEXT = 'DELETE_TEXT';
export const SET_LINE_LENGTH = 'SET_LINE_LENGTH';
export const SHOW_PRELOADER = 'SHOW_PRELOADER';
export const HIDE_PRELOADER = 'HIDE_PRELOADER';
